export const PRODUCT_CARD = {
    PRODUCT_NAME: "PRODUCT_NAME",
    PRODUCT_COLOR: "PRODUCT_COLOR",
    PRODUCT_PRICE: "PRODUCT_PRICE",
    PRODUCT_IMAGE: "PRODUCT_IMAGE",
    CART_BUTTON: "CART_BUTTON",
}

export const LANDING_SCREEN = {
    VIEW_CART_BUTTON: "VIEW_CART_BUTTON"
}

export const CART_DETAIL = {
    EMPTY_CART_BUTTON: "EMPTY_CART_BUTTON",
}